# Generated by Django 4.2.13 on 2025-11-15 17:41

from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', validators=[games.models.validate_image_size]),
        ),
    ]
