# Generated by Django 4.2.13 on 2025-11-16 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
